### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'nei'

### ISSUE THREAD

**Issue by tekkamanmaverick** [jzuhone/pyxsim#12]
source_model = pyxsim.ThermalSourceModel("apec", 0.05, 11.0, 10000, Zmet=0.3)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-b58891918291> in <module>()
----> 1 source_model = pyxsim.ThermalSourceModel("apec", 0.05, 11.0, 10000, Zmet=0.3)

/home/share/software/anaconda2/lib/python2.7/site-packages/pyxsim/source_models.pyc in __init__(self, spectral_model, emin, emax, nchan, temperature_field, emission_measure_field, kT_min, kT_max, n_kT, kT_scale, Zmet, var_elem, method, thermal_broad, model_root, model_vers, nei, nolines, abund_table, prng)
    163                                              model_vers=model_vers,
    164                                              nolines=nolines, nei=nei,
--> 165                                              abund_table=abund_table)
    166         self.var_elem_keys = self.spectral_model.var_elem_names
    167         self.var_ion_keys = self.spectral_model.var_ion_names

/home/share/software/anaconda2/lib/python2.7/site-packages/pyxsim/spectral_models.pyc in __init__(self, emin, emax, nchan, var_elem, model_root, model_vers, thermal_broad, nolines, abund_table, nei)
     83                                              apec_root=model_root, apec_vers=model_vers,
     84                                              broadening=thermal_broad, nolines=nolines,
---> 85                                              abund_table=abund_table, nei=nei)
     86         self.nchan = self.nbins
     87 

TypeError: __init__() got an unexpected keyword argument 'nei'

**Comment by jzuhone** [comment]
Did you update SOXS? This version of pyXSIM needs SOXS 2.1.0. Sorry, I suspect that something went wrong in the dependencies from anaconda.

**Comment by tekkamanmaverick** [comment]
Thank you. 
I have updated SOXS.  Everything is all right now.
