### ISSUE TITLE
Photon generating outside the specified area

### ISSUE THREAD

**Issue by tekkamanmaverick** [jzuhone/pyxsim#18]
Hi John,

I use ds.sphere to generate photons in the specified area of illustris-1. But I find the region where the photons are generated is far beyond expected. I get the event data (RA, Dec) from the phlist.fits and draw a cross though the region covers the fov.

**Comment by jzuhone** [comment]
I’ll have to see a script and I’ll need to see a picture of what you’re describing

**Comment by tekkamanmaverick** [comment]
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from astropy.io import fits

hdu = fits.open('snap_131_sp_phlist.fits')

E = hdu['PHLIST'].data['ENERGY']
RA = hdu['PHLIST'].data['RA']
DEC = hdu['PHLIST'].data['DEC']

p = plt.scatter(RA,DEC,c=E)



picture
https://github.com/tekkamanmaverick/symphony/blob/master/cross.png

**Comment by jzuhone** [comment]
Sorry that this never got resolved. It looks like you were straddling a periodic boundary perhaps, but not sure. Please reopen if necessary.
