### ISSUE TITLE
Is the type of photons projection perspective or parallel?

### ISSUE THREAD

**Issue by tekkamanmaverick** [jzuhone/pyxsim#19]
Hi,
I am not sure the type of photons projection. If the extension of the photons in the line of sight is very large, the perspective projection will be more reasonable.

**Comment by jzuhone** [comment]
I think this is correct. Leaving this issue open in case we want to try to resolve it.

**Comment by jzuhone** [comment]
@tekkamanmaverick after several years we added "internal" observers to pyXSIM for photon generation (though we do not yet have it for X-ray field projections).
