### ISSUE TITLE
Discrepancy between the density image and the final X-ray image of a halo from IllustrisTNG.

### ISSUE THREAD

**Issue by sandhya0892** [jzuhone/pyxsim#22]
Hi @jzuhone ,

I have followed the instructions on how to produce the X-ray image of a halo. I have attached the image below. I have also attached the corresponding density profile. I have used different X-ray instruments and different values of exposure time etc. but this the best image that I could get. However, it does not seem to represent the halo in question. What changes should I incorporate to get a better image or this is the image that I should expect?

`ds = yt.load("cutout_1.hdf5")
sp = ds.sphere("max",(0.2,"Mpc"))
Zmet = ("PartType0","GFM_Metallicity")
source_model = pyxsim.ThermalSourceModel("apec",0.05,10.0,10000,Zmet=Zmet)
exp_time = (500., "ks")
area = (2000.0, "cm**2")
redshift = 0.0
photons = pyxsim.PhotonList.from_data_source(sp, redshift, area, exp_time, source_model,center=sp.center, dist=(20.,"Mpc"))
events_z = photons.project_photons("z", (45.,30.), absorb_model="tbabs", nH=0.04)
events_z.write_simput_file("cluster1", overwrite=True)
soxs.instrument_simulator("cluster1_simput.fits", "evt1.fits", (30.0, "ks"),"lynx_hdxi",[45., 30.], overwrite=True)
soxs.write_image("evt1.fits", "img1.fits", emin=0.5, emax=20.0, overwrite=True)
fig = aplpy.FITSFigure("img1.fits")
fig.show_colorscale(cmap='arbre', vmin=0.0, stretch='sqrt')
fig.recenter(45., 30., radius=0.1)
fig.save("cluster1_img.png")`

![cutout_1_Slice_z_density](https://user-images.githubusercontent.com/50319775/59145859-53645800-8a07-11e9-931a-83b05e2d6b2e.png)
![cluster1_img](https://user-images.githubusercontent.com/50319775/59145866-5b23fc80-8a07-11e9-8771-b7e2b82e75fd.png)

Thanks and regards,
Sandhya

**Comment by sandhya0892** [comment]
Hi, @jzuhone,

I just have a few more thing to add. I had even tried using the position of the group halo instead of "max" in the photon list and set the redshift to '0.05' instead of using the distance parameter. 
The position of the group halo instead of "max" does not seem to change anything. However, for a different halo, I found completely different plots:
The density for the same is :
![cutout_0_Slice_z_density](https://user-images.githubusercontent.com/50319775/59434723-bf7cfc80-8e09-11e9-8df0-6c76b2fd3d6d.png)
The first one is for 'athena_xifu' instrument:
![cluster0_img](https://user-images.githubusercontent.com/50319775/59434670-a5dbb500-8e09-11e9-945b-f1f35ba5cd72.png)
This one is for 'chandra_acisi_cy20':
![cluster01_img](https://user-images.githubusercontent.com/50319775/59434693-b2600d80-8e09-11e9-8933-16ff7f990bdd.png)
I believe the plots are coming out to be different because of the difference in density plots? What other changes do you suggest?

Thanks and regards,
Sandhya

**Comment by jzuhone** [comment]
@sandhya0892, sorry I never got to this. did you ever figure this out?

**Comment by jzuhone** [comment]
Closing since there was no further discussion.
