### ISSUE TITLE
Maybe the current version does not support python3.7

### ISSUE THREAD

**Issue by tekkamanmaverick** [jzuhone/pyxsim#24]
Hi John,
I got some trouble when I tried to convolve the events.
The output:
astropy.units.core.UnitConversionError: '' (dimensionless) and 'keV' (energy) are not convertible

However, my previous version of python (python2) is work. I think this is the problem of version.

**Comment by jzuhone** [comment]
Hi @tekkamanmaverick, this is a SOXS issue and not a pyXSIM issue. 

It's been fixed:

https://github.com/XRStools/soxs/issues/7

If you git clone and install a new version of SOXS from source at `http://github.com/XRStools/soxs`, this will fix the issue.
