### ISSUE TITLE
Question: approximate x-ray beam for chest imaging

### ISSUE THREAD

**Issue by kingjr** [jzuhone/pyxsim#25]
Hi all, thanks a lot for this very nice package.

I'm trying to simulate a Chest X-Ray image from a known volumetric "CT" scan. The former is a projection of the latter from a focal x-ray source:
![image](https://user-images.githubusercontent.com/4881164/80636514-ea8e3000-8a5d-11ea-9c67-556ebaf493ed.png)

I did see the tutorial http://hea-www.cfa.harvard.edu/~jzuhone/pyxsim/light_cone.html here, but it is still relatively slow.

I was wondering whether you had any recommendation to get a perhaps more coarse approximation at a faster speed.

Thank you

**Comment by jzuhone** [comment]
Closing this because it is out of scope for the pyXSIM package.
