### ISSUE TITLE
The normalization of the model

### ISSUE THREAD

**Issue by tekkamanmaverick** [jzuhone/pyxsim#28]
Hi John,

I have noticed the changelog of version 2.3.0. You have replaced n_H+ with n_H. So, is the norm (10^{-14}\int{n_en_p}dV/[4\pi(1+z)^2D_A^2]) which you defined in https://hea-www.cfa.harvard.edu/soxs/users_guide/spectra.html still correct?

**Comment by jzuhone** [comment]
@tekkamanmaverick technically yes--if by n_p we mean the total number of hydrogen atoms. But that's a bit too ambiguous, so we need to probably fix the name of the normalization.

For most applications, when you are dealing with gas that is hot and nearly fully ionized, this change should not matter whatsoever.
