### ISSUE TITLE
How to load the IllustrisTNG snapshot in HDF5 format using yt?

### ISSUE THREAD

**Issue by WangYun1995** [jzuhone/pyxsim#29]
Hi,

I learned that yt is a powerful tool for analyzing cosmological simulation. And IllustrisTNG is one of the state-of-art hydrodynamical simulations. 

However, I didn't see any example about how to load TNG snapshot and other TNG data by yt in the website of yt([https://yt-project.org/doc/index.html](url)).

So is there any method to load TNG snapshot using yt?

**Comment by jzuhone** [comment]
@WangYun1995 this sounds like a yt issue instead of a pyXSIM issue. I would post any yt-related issues at https://github.com/yt-project/yt/issues. 

Feel free to tag me (@jzuhone) there.
