### ISSUE TITLE
The emissivity calculation

### ISSUE THREAD

**Issue by qinyuxian** [jzuhone/pyxsim#33]
Hi John,

In my opinion, the emissivity (\epsilon = n_e n_H \Lambda_E(T,Z)) should be calculated in the comoving frame. However, it seems that pyXSIM uses the proper density to calculate the emission measure directly. The physical picuture what I understand may be can illustrated in the following figure. What do you think about it?

Thank you and best wishes.

![t16_three_distances](https://user-images.githubusercontent.com/59043983/119472570-ede90d80-bd7c-11eb-8df7-7bc75d553a85.gif)

**Comment by qinyuxian** [comment]
I think I was wrong. Sorry for troubling you.

**Comment by qinyuxian** [comment]
However, I think of another question. If I use the data from the snapshot of z = 0.1 and observer them at z=0.2. The comoving density is constant. Which physical densities shall I use, at z=0.1 or at z=0.2? Thank you.

**Comment by jzuhone** [comment]
Which redshift does the source emit at?

**Comment by qinyuxian** [comment]
It emits at z=0.2. However, I do not have snapshot at z=0.2. So I used the snapshot of z=0.1 instead of z=0.2.

**Comment by jzuhone** [comment]
If it emits at z = 0.2 you need the snapshot at z = 0.2.

**Comment by qinyuxian** [comment]
In fact, the positions, velocities and physical properties of the simulation are stored only at a discrete set of redshifts. If I want to make the light cone, such problem will arises.

**Comment by jzuhone** [comment]
This is always the case with light cone simulations--nothing unusual. 

Unless you have another question pertinent to the emissivity I'll be closing this issue.

**Comment by qinyuxian** [comment]
It is OK to close.
