### ISSUE TITLE
Installation issues due to incorrect version of dependancy

### ISSUE THREAD

**Issue by DavidT3** [jzuhone/pyxsim#42]
I haven't used pyXSIM in quite a while, so did a clean installation, and if you install the module on a clean conda environment using the conda release the module is unusable due to a failure on import.

This failure occurs because the unyt module is not installed, which in turn happens because pyXSIM requires YT > v4.0 and the conda installation allows it to install v3.6 of YT.

**Comment by jzuhone** [comment]
@DavidT3 I think that this is fixed in the latest version, but let me know if not.

**Comment by jzuhone** [comment]
Closing, please let me know if it needs re-opening.
