### ISSUE TITLE
The Solar Abundance Table

### ISSUE THREAD

**Issue by tekkamanmaverick** [jzuhone/pyxsim#52]
Hi John,

Could you append [Wiersma et al.](https://ui.adsabs.harvard.edu/abs/2009MNRAS.399..574W/abstract) to the Solar abundance table in pyXSIM? This abundances were used in Eagle and Illustris.

Thand you and best wishes.

**Comment by jzuhone** [comment]
@tekkamanmaverick I think that this is automatically included with the Cloudy abundances in pyXSIM/SOXS (setting `abund_table="cl17.03"`). Let me know if not. The problem with using the Wiersma et al. table by itself is that it doesn't include all of the elements SOXS needs to populate.

**Comment by tekkamanmaverick** [comment]
Hi John,

Thanks for your kindly reply. 
I don't think the Wiersma et al. table is cl17.03. The Cloudy version they used is 07.02. For example, the C and the S abundance are different. You can compare the Table 1 of Wiersma et al. and the cl17.03 defined in SOXS. [Nelson et al.](https://ui.adsabs.harvard.edu/abs/2015A%26C....13...12N/abstract) said: "To convert to solar metallicity, divide by 0.0127 (the primordial solar metallicity)."
