### ISSUE TITLE
Can I combine two Photon Lists from two different Data Sources? 

### ISSUE THREAD

**Issue by dingjiao22** [jzuhone/pyxsim#7]
I have two data sources:
ds=yt.load("Illustris-3/snap_134/snap_134.0.hdf5")
dds=yt.load("Illustris-3/snap_132/snap_132.0.hdf5"),
each is matched with a redshift and can create an image of the photons.
I want to have an image that shows photons generated from both Data Sources, but I find it's impossible to plus two Photon Lists together:
"RuntimeError: The values for the parameter 'Dimension' in the two inputs are not identical"
So is it possible to combine  two Photon Lists from two different Data Sources? Or are there any solutions to create a photon image that includes photons generated from two Data Sources? 
Thank you very much!!

**Comment by jzuhone** [comment]
Have you updated to pyXSIM 2.0? This should no longer be an issue in that version, if I remember correctly.

**Comment by dingjiao22** [comment]
I update to pyXSIM 2.0 and it works.
Thank you very much!!
