### ISSUE TITLE
Can I draw an absorption line of a specific atom?

### ISSUE THREAD

**Issue by dingjiao22** [jzuhone/pyxsim#8]
When I generate an Event List, I use "tbabs" absorption modol and get a spectrum from it.
But besides, I also want to get and draw an absorption line of a specific atom, such as O or H, in the spectrum, like the  emission line from dark matter particles in your examples.
Is that possible? Since I don't know much about the foreground galactic absorption.
Thank you very much!!

PS: Thank you for solving my previous issue!

**Comment by jzuhone** [comment]
@dingjiao22 sorry, somehow I missed this issue. my apologies. 

We don't have this capability in the code yet, but it would be nice. It also may depend a bit on whether or not you are interested in absorption intrinsic to the source or just foreground galactic absorption.

**Comment by dingjiao22** [comment]
Thank  you so much!
I only consider the foreground galactic absorption.
